export const events = [
    {
      _id: "1",
      title: "Music Concert",
      image: "https://via.placeholder.com/150",
      seatsAvailable: 50,
      ticketPrice: 20,
      type: "paid",
      location: "New York",
      capacity: 100,
      date: "2024-12-15",
      duration: 3,
      description: "Enjoy a night of amazing music.",
    },
    {
      _id: "2",
      title: "Art Workshop",
      image: "https://via.placeholder.com/150",
      seatsAvailable: 10,
      ticketPrice: 0,
      type: "free-limited",
      location: "Los Angeles",
      capacity: 20,
      date: "2024-12-20",
      duration: 2,
      description: "Learn painting techniques.",
    },
    {
      _id: "3",
      title: "Tech Conference",
      image: "https://via.placeholder.com/150",
      seatsAvailable: Infinity,
      ticketPrice: 0,
      type: "free-unlimited",
      location: "San Francisco",
      capacity: Infinity,
      date: "2024-12-25",
      duration: 5,
      description: "Explore the latest in technology.",
    },
  ];
  